name: Terraform deploy resources

on:
  push:
    branches:
      - kuku
      - kuku1
  #pull_request:
  #  branches:
  #    - main  
  workflow_dispatch:

jobs:
  terraform:
    name: 'Deploy using Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      TF_ACTIONS_VERSION: 1.3.6
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Terraform Format'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_ACTIONS_VERSION }}
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: "./terraform/deploy"
          tf_actions_comment: true

      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_ACTIONS_VERSION }}
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: "./terraform/deploy"

      - name: 'Terraform Validate'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_ACTIONS_VERSION }}
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: "./terraform/deploy"

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_ACTIONS_VERSION }}
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: "./terraform/deploy"

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: ${{ env.TF_ACTIONS_VERSION }}
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: "./terraform/deploy"