name: Deploy to Production

on:
  workflow_run:
    workflows: ["Terraform deploy resources"]
    types:
      - completed
    branches:
      - main

  workflow_dispatch:

env:
  SLOT_NAME: dev
  WEBAPP_NAME: msapi-function-app
  RESOURCE_GROUP: msapi_rsg

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
    
    - name: Log into Azure CLI with service principal
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Swap slots
      run: az webapp deployment slot swap -s ${{ env.SLOT_NAME }} -n ${{ env.WEBAPP_NAME }} -g ${{ env.RESOURCE_GROUP }}
